### PR TITLE
Fix exec to set the mode

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by madchap** [comment]
It seems this is not fixed indeed. It is always doing something if selinux is disabled, so the return code is never 0.

**Comment by ghoneycutt** [comment]
@madchap does this branch fix the issue for you?

**Comment by madchap** [comment]
@ghoneycutt, yes it seems to do the job. Thanks.

**Comment by ghoneycutt** [comment]
Released in v1.3.2

Thank you!

**Pull request merged**
